### ISSUE TITLE
lidt mere info

### ISSUE THREAD

**Issue by dartfrogdk** [turbokongen/kamstrup-homeassistant#1]
Hejsa, jeg vil gerne have min kamstrup ind på homesssistant men kan du ikke vise hvordan du har forbundet det

**Comment by turbokongen** [comment]
Heisann. Dette repository hadde jeg glemt. Det er blitt erstattet med hass-AMS.(Se info i repository) https://github.com/turbokongen/hass-AMS
Dette kan lastes ned via HACS eller legges manuelt inn via custom_components

**Comment by dartfrogdk** [comment]
Hvad med det tekniske


søn. 1. aug. 2021 14.45 skrev John Arild Berentsen ***@***.***

**Comment by turbokongen** [comment]
Denne sitter i måleren(Levert av strømselskapet): https://www.ymber.no/getfile.php/4425345.484.slip7mlzazkiwa/Datablad+Kamstrup+HAN+modul.pdf?&force=1
Mbus usb adapter i PC: 
https://www.aliexpress.com/item/32719562958.html?spm=a2g0s.9042311.0.0.c8314c4dpbv1pv https://www.aliexpress.com/item/32751482255.html?spm=2114.10010108.1000014.1.2a3189f8fCOsSM https://www.aliexpress.com/item/32834331647.html?spm=a2g0o.detail.1000060.1.74cfdcd4qts4jp
Kabel fra rj-45 pin 1 og 2 til Mbus adapter: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bjorseth.no%2Fblog%2F2019%2F08%2Freading-information-from-your-ams-power-meter-02-attaching-the-usb-to-mbus-adapter-to-the-ams-smart-meter%2F&psig=AOvVaw2nTAXSH_NOJ9rZQmBidrVb&ust=1627913824560000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPDg29uBkPICFQAAAAAdAAAAABAO
